---
title: "Class 3/5/2020"
author: "Lainey Newman"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(googlesheets4)
library(infer)
library(tidyverse)
library(janitor)
```


```{r echo=FALSE}

sheets_deauth()

sheet <- read_sheet("14HmwN2cEVAJHupuehCuLdwG9BXtR3COrxDgaaylLhkA") %>%
  clean_names() %>%
  mutate(perc_red = red / (red + white))
  
ggplot(sheet, aes(x = perc_red)) +
  geom_histogram()

urn <- tibble(bead_ID = 1:10000, 
              color = c(rep("red", 2000), rep("white", 8000)))

sample_urn <- urn %>%
  rep_sample_n(size = 25, reps = 51) %>%
  group_by(replicate) %>%
  summarize(red_sum = sum(color == "red")) %>%
  mutate(perc_red = red_sum/25)


sample_urn %>%
  ggplot(aes(perc_red)) + geom_histogram()

use_shovel <- function(urn) {
  urn %>%
  rep_sample_n(size = 25, reps = 51) %>%
  group_by(replicate) %>%
  summarize(red_sum = sum(color == "red")) %>%
  mutate(perc_red = red_sum/25)
}

shovel_results <- tibble(ball_ID = 1:3,
                         results = map(ball_ID, ~ use_shovel(urn)))
```

```{r}
shovel_results[[2]][[2]] %>%
  ggplot(aes(perc_red)) + geom_histogram()
```

